server:
  port: 8080
  
logging:
  config: classpath:logback-spring.xml
  
spring:
  application:
    name: classfinal-web
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  
  resources:
    static-locations: classpath:/static/
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+08:00
  
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    suffix: .ftl
  
  http:
    encoding:
      charset: UTF-8
      force: true
